In [1]:
import numpy as np

np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
m = np.array([[1,2,3],[4,5,6]])

print(m)

[[1 2 3]
 [4 5 6]]


In [4]:
print(m.shape)

(2, 3)


In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
m = np.array([[1,2,3],[4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


In [12]:
m.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [15]:
np.arange(1,7).reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.arange(1,7).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
m = np.array([[1,2,3],[4,5,6]])
print(m.reshape(-1))

[1 2 3 4 5 6]
